openapi: 3.1.0
info:
  title: SwiftMCP Demo Calculator API
  version: "1.0.0"
  description: >
    This API exposes a set of tools provided by the Calculator server.
    Each tool is callable via its dedicated endpoint (e.g. POST /calculator/greet).
servers:
  - url: https://localhost
    description: Local development server
paths:
  /calculator/add:
    post:
      summary: Add two numbers
      operationId: add
      description: "Custom description: Performs addition of two numbers."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: integer
                  description: First number to add.
                b:
                  type: integer
                  description: Second number to add.
              required:
                - a
                - b
      responses:
        "200":
          description: The sum of a and b.
          content:
            application/json:
              schema:
                type: integer
        "400":
          description: Invalid input.
  /calculator/subtract:
    post:
      summary: Subtract two numbers
      operationId: subtract
      description: Subtracts the second integer from the first and returns the difference. Parameter b defaults to 3 if not provided.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: integer
                  description: Number to subtract from.
                b:
                  type: integer
                  description: Number to subtract (optional; defaults to 3).
              required:
                - a
      responses:
        "200":
          description: The difference between a and b.
          content:
            application/json:
              schema:
                type: integer
  /calculator/testArray:
    post:
      summary: Test array processing
      operationId: testArray
      description: "Custom description: Tests array processing and returns a comma‐separated string."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: array
                  items:
                    type: integer
                  description: Array of integers to process.
              required:
                - a
      responses:
        "200":
          description: A comma‐separated string representing the array.
          content:
            application/json:
              schema:
                type: string
  /calculator/multiply:
    post:
      summary: Multiply two numbers
      operationId: multiply
      description: Multiplies two integers and returns their product.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: integer
                  description: First factor.
                b:
                  type: integer
                  description: Second factor.
              required:
                - a
                - b
      responses:
        "200":
          description: The product of a and b.
          content:
            application/json:
              schema:
                type: integer
  /calculator/divide:
    post:
      summary: Divide two numbers
      operationId: divide
      description: Divides the numerator by the denominator and returns the quotient. Denominator defaults to 1.0 if not provided.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numerator:
                  type: number
                  description: Number to be divided.
                denominator:
                  type: number
                  description: Number to divide by (optional; defaults to 1.0).
              required:
                - numerator
      responses:
        "200":
          description: The quotient of numerator divided by denominator.
          content:
            application/json:
              schema:
                type: number
  /calculator/greet:
    post:
      summary: Greet a person
      operationId: greet
      description: Shows a greeting message using the provided name.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the person to greet.
              required:
                - name
      responses:
        "200":
          description: Greeting message.
          content:
            application/json:
              schema:
                type: string
  /calculator/ping:
    post:
      summary: Ping the server
      operationId: ping
      description: A simple ping function that returns "pong".
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        "200":
          description: "pong response."
          content:
            application/json:
              schema:
                type: string