//
//  MCPExtensionRegistry.swift
//  SwiftMCP
//
//  Prototype runtime registry for tools contributed by extensions.
//  Populated at startup by code generated by SwiftMCPAggregator build plugin.
//

import Foundation

/// One tool contributed by an extension.
///
/// `metadata` describes the tool for `tools/list`. `call` invokes it with the
/// pre-enriched argument dictionary; the closure is responsible for typed
/// argument extraction and forwarding to the user's function.
public struct MCPExtensionToolEntry: Sendable {
    public let metadata: MCPToolMetadata
    public let call: @Sendable (Any, JSONDictionary) async throws -> Encodable & Sendable

    public init(
        metadata: MCPToolMetadata,
        call: @escaping @Sendable (Any, JSONDictionary) async throws -> Encodable & Sendable
    ) {
        self.metadata = metadata
        self.call = call
    }
}

/// Process-wide registry of extension-defined tool contributions, keyed by
/// the receiving server type.
///
/// Bootstrap functions emitted by `SwiftMCPAggregator` push entries here.
/// `@MCPServer`-generated `mcpToolMetadata` and `callTool` consult it at
/// runtime to surface and dispatch tools defined in extensions.
public enum MCPExtensionRegistry {
    private static let lock = NSLock()
    nonisolated(unsafe) private static var byType: [ObjectIdentifier: [MCPExtensionToolEntry]] = [:]

    /// Register one or more extension tools for a server type.
    /// Idempotent on `(typeID, tool name)` — duplicates are dropped.
    public static func register<Server>(_ type: Server.Type, tools: [MCPExtensionToolEntry]) {
        lock.lock(); defer { lock.unlock() }
        let key = ObjectIdentifier(type)
        var existing = byType[key] ?? []
        let existingNames = Set(existing.map(\.metadata.name))
        for entry in tools where !existingNames.contains(entry.metadata.name) {
            existing.append(entry)
        }
        byType[key] = existing
    }

    /// All tools registered for a given server type.
    public static func tools<Server>(for type: Server.Type) -> [MCPExtensionToolEntry] {
        lock.lock(); defer { lock.unlock() }
        return byType[ObjectIdentifier(type)] ?? []
    }
}
