//
//  Codegen.swift
//  SwiftMCPAggregatorTool
//
//  Renders the aggregated `extension <ServerType>.Client { ... }` source
//  files from the methods discovered by `ExtensionFinder`.
//

import Foundation

// MARK: - File-level output

func sanitizeIdentifier(_ raw: String) -> String {
    guard !raw.isEmpty else { return "Module" }
    var out = ""
    var first = true
    for character in raw {
        if first {
            if character.isLetter || character == "_" { out.append(character) } else { out.append("_") }
            first = false
        } else {
            if character.isLetter || character.isNumber || character == "_" {
                out.append(character)
            } else {
                out.append("_")
            }
        }
    }
    return out.isEmpty ? "Module" : out
}

func generateOutput(moduleName: String, byType: [String: [DiscoveredMethod]], imports: Set<String>) -> String {
    var out = ""
    out.append("// Generated by SwiftMCPAggregatorTool — DO NOT EDIT.\n")
    out.append("// Aggregated Client extensions for module \(moduleName).\n\n")

    var importsToEmit = imports
    importsToEmit.insert("SwiftMCP")
    importsToEmit.remove(moduleName)
    for imp in importsToEmit.sorted() {
        out.append("import \(imp)\n")
    }
    out.append("\n")

    for type in byType.keys.sorted() {
        let methods = byType[type] ?? []
        guard !methods.isEmpty else { continue }
        out.append(emitClientExtension(forType: type, methods: methods))
    }
    return out
}

/// Emits a single `extension <Type>.Client { ... }` block, grouping
/// methods by their `#if` condition.
private func emitClientExtension(forType type: String, methods: [DiscoveredMethod]) -> String {
    var out = "extension \(type).Client {\n"

    // Group by `#if` condition (empty string = unconditional). Within
    // each group, emit methods in source order. Empty-condition group
    // first so the most common case is at the top.
    let grouped = Dictionary(grouping: methods, by: \.ifConfigCondition)
    let conditions = grouped.keys.sorted { lhs, rhs in
        if lhs.isEmpty { return true }
        if rhs.isEmpty { return false }
        return lhs < rhs
    }

    for condition in conditions {
        let group = grouped[condition] ?? []
        if !condition.isEmpty {
            out.append("\n    #if \(condition)\n")
        }
        for method in group {
            out.append("\n")
            out.append(emitClientMethod(method))
        }
        if !condition.isEmpty {
            out.append("\n    #endif\n")
        }
    }

    out.append("}\n\n")
    return out
}

// MARK: - Per-method dispatch

func emitClientMethod(_ method: DiscoveredMethod) -> String {
    switch method.kind {
    case .tool(let wireName):
        return emitToolClientMethod(method, wireToolName: wireName)
    case .resource(let templates):
        return emitResourceClientMethod(method, templates: templates)
    case .prompt:
        return emitPromptClientMethod(method)
    }
}

// MARK: - Tool emission

func emitToolClientMethod(_ method: DiscoveredMethod, wireToolName: String) -> String {
    var out = ""
    out.append(docCommentBlock(method))

    let signature = method.parameters.map(parameterSignature).joined(separator: ", ")
    let effects = effectSpecifiers(isAsync: method.isAsync, throwsKeyword: method.throwsKeyword ?? "throws")
    let hasReturn = method.returnTypeString != nil && method.returnTypeString != "Void"
    let returnTypeText = method.returnTypeString.map { "\($0).MCPClientReturn" }
    let returnClause = hasReturn ? " -> \(returnTypeText!)" : ""
    let hasParams = !method.parameters.isEmpty

    out.append("    public func \(method.functionName)(\(signature))\(effects)\(returnClause) {\n")
    out.append(encodedArgumentsLines(parameters: method.parameters, indent: "        "))

    let argumentsName = toolArgumentsName(hasParams: hasParams, isAsync: method.isAsync, out: &out)

    let call = hasParams
        ? "proxy.callTool(\"\(wireToolName)\", arguments: \(argumentsName))"
        : "proxy.callTool(\"\(wireToolName)\")"
    let invocation: String = method.isAsync
        ? "try await \(call)"
        : "try MCPClientBlocking.call { try await \(call) }"
    out.append("        let text = \(invocation)\n")

    if hasReturn {
        out.append("        return try MCPClientResultDecoder.decode(\(returnTypeText!).self, from: text)\n")
    } else {
        out.append("        _ = try MCPClientResultDecoder.decode(Void.self, from: text)\n")
        out.append("        return\n")
    }

    out.append("    }\n")
    return out
}

/// Computes the variable name to reference encoded arguments and, when
/// the call site is synchronous, emits the `let capturedArguments` line.
private func toolArgumentsName(hasParams: Bool, isAsync: Bool, out: inout String) -> String {
    if hasParams && !isAsync {
        out.append("        let capturedArguments = arguments\n")
        return "capturedArguments"
    }
    if hasParams {
        return "arguments"
    }
    return ""
}

// MARK: - Resource emission

func emitResourceClientMethod(_ method: DiscoveredMethod, templates: [String]) -> String {
    var out = ""
    out.append(docCommentBlock(method))
    out.append(resourceMethodSignature(method))
    out.append(encodedArgumentsLines(parameters: method.parameters, indent: "        "))

    let hasParams = !method.parameters.isEmpty
    let argumentsName = resourceArgumentsName(hasParams: hasParams, isAsync: method.isAsync, out: &out)

    out.append(resourceURIConstructionLines(method: method, templates: templates, argumentsName: argumentsName))

    let readCall = method.isAsync
        ? "try await proxy.readResource(uri: uri)"
        : "try MCPClientBlocking.call { try await proxy.readResource(uri: uri) }"
    out.append("        let contents = \(readCall)\n")

    out.append(resourceReturnLines(method: method))
    out.append("    }\n")
    return out
}

private func resourceMethodSignature(_ method: DiscoveredMethod) -> String {
    let signature = method.parameters.map(parameterSignature).joined(separator: ", ")
    let effects = effectSpecifiers(isAsync: method.isAsync, throwsKeyword: method.throwsKeyword ?? "throws")
    let hasReturn = method.returnTypeString != nil && method.returnTypeString != "Void"
    let returnText = method.returnTypeString.map { "\($0).MCPClientReturn" }
    let returnClause = hasReturn ? " -> \(returnText!)" : ""
    return "    public func \(method.functionName)(\(signature))\(effects)\(returnClause) {\n"
}

private func resourceArgumentsName(hasParams: Bool, isAsync: Bool, out: inout String) -> String {
    if hasParams && !isAsync {
        out.append("        let capturedArguments = arguments\n")
        return "capturedArguments"
    }
    if hasParams {
        return "arguments"
    }
    return "[:]"
}

/// Emits the `let uri = ...` block for a resource method. Handles single
/// and multi-template cases separately.
private func resourceURIConstructionLines(
    method: DiscoveredMethod,
    templates: [String],
    argumentsName: String
) -> String {
    let ordered = templates.sorted { resourceTemplateVariableCount($0) > resourceTemplateVariableCount($1) }
    if ordered.count <= 1 {
        let template = ordered.first ?? ""
        let escaped = template.replacingOccurrences(of: "\"", with: "\\\"")
        return "        let uri = try \"\(escaped)\".constructURI(with: \(argumentsName))\n"
    }
    var out = "        let uri: URL\n"
    for (idx, template) in ordered.enumerated() {
        let vars = resourceTemplateVariables(in: template)
        let cond = vars.isEmpty
            ? "true"
            : vars.map { "\(argumentsName)[\"\($0)\"] != nil" }.joined(separator: " && ")
        let keyword = idx == 0 ? "if" : "else if"
        let escaped = template.replacingOccurrences(of: "\"", with: "\\\"")
        out.append("        \(keyword) \(cond) {\n")
        out.append("            uri = try \"\(escaped)\".constructURI(with: \(argumentsName))\n")
        out.append("        }\n")
    }
    out.append("        else {\n")
    out.append("            throw MCPServerProxyError.communicationError("
        + "\"No resource template matched for \(method.functionName)\")\n")
    out.append("        }\n")
    return out
}

/// Emits the trailing `return ...` / decoding block for a resource
/// method based on its declared return type.
private func resourceReturnLines(method: DiscoveredMethod) -> String {
    let hasReturn = method.returnTypeString != nil && method.returnTypeString != "Void"
    let returnType = method.returnTypeString ?? "Void"
    let returnText = method.returnTypeString.map { "\($0).MCPClientReturn" }
    if !hasReturn {
        return "        return\n"
    }
    switch returnType {
    case "MCPResourceContent", "GenericResourceContent":
        var out = "        guard let content = contents.first else {\n"
        out.append("            throw MCPServerProxyError.communicationError("
            + "\"Resource \(method.functionName) returned no content\")\n")
        out.append("        }\n")
        out.append("        return content\n")
        return out
    case "[MCPResourceContent]", "[GenericResourceContent]":
        return "        return contents\n"
    case "Data":
        var out = "        if let blob = contents.first?.blob { return blob }\n"
        out.append("        if let text = contents.first?.text {\n")
        out.append("            return try MCPClientResultDecoder.decode(Data.self, from: text)\n")
        out.append("        }\n")
        out.append("        throw MCPServerProxyError.communicationError("
            + "\"Resource \(method.functionName) returned no blob content\")\n")
        return out
    default:
        var out = "        guard let text = contents.first?.text else {\n"
        out.append("            throw MCPServerProxyError.communicationError("
            + "\"Resource \(method.functionName) returned no text content\")\n")
        out.append("        }\n")
        out.append("        return try MCPClientResultDecoder.decode("
            + "\(returnText!).self, from: text)\n")
        return out
    }
}

// MARK: - Prompt emission

func emitPromptClientMethod(_ method: DiscoveredMethod) -> String {
    var out = ""
    out.append(docCommentBlock(method))

    let signature = method.parameters.map(parameterSignature).joined(separator: ", ")
    let effects = effectSpecifiers(isAsync: method.isAsync, throwsKeyword: method.throwsKeyword ?? "throws")
    let hasParams = !method.parameters.isEmpty

    out.append("    public func \(method.functionName)(\(signature))\(effects) -> PromptResult {\n")
    out.append(encodedArgumentsLines(parameters: method.parameters, indent: "        "))

    let argumentsName = toolArgumentsName(hasParams: hasParams, isAsync: method.isAsync, out: &out)

    let call = hasParams
        ? "proxy.getPrompt(name: \"\(method.functionName)\", arguments: \(argumentsName))"
        : "proxy.getPrompt(name: \"\(method.functionName)\")"
    let invocation: String = method.isAsync
        ? "return try await \(call)"
        : "return try MCPClientBlocking.call { try await \(call) }"
    out.append("        \(invocation)\n")
    out.append("    }\n")
    return out
}

// MARK: - Shared helpers

func parameterSignature(_ param: DiscoveredParameter) -> String {
    let label: String
    if param.label == "_" {
        label = "_ \(param.name)"
    } else if param.label != param.name {
        label = "\(param.label) \(param.name)"
    } else {
        label = param.name
    }
    var sig = "\(label): \(param.typeString)"
    if let defaultValue = param.defaultValue, !defaultValue.isEmpty { sig += " = \(defaultValue)" }
    return sig
}

func effectSpecifiers(isAsync: Bool, throwsKeyword: String) -> String {
    var parts: [String] = []
    if isAsync { parts.append("async") }
    parts.append(throwsKeyword)
    return " " + parts.joined(separator: " ")
}

func encodedArgumentsLines(parameters: [DiscoveredParameter], indent: String) -> String {
    guard !parameters.isEmpty else { return "" }
    var out = "\(indent)var arguments: JSONDictionary = [:]\n"
    for param in parameters {
        let encode = "try MCPClientArgumentEncoder.encode(\(param.name))"
        if param.isOptional {
            out.append("\(indent)if let \(param.name) { arguments[\"\(param.name)\"] = \(encode) }\n")
        } else {
            out.append("\(indent)arguments[\"\(param.name)\"] = \(encode)\n")
        }
    }
    return out
}

func docCommentBlock(_ method: DiscoveredMethod) -> String {
    var lines: [String] = []
    if let doc = method.docComment, !doc.isEmpty {
        for line in doc.split(separator: "\n") {
            lines.append(String(line))
        }
    }
    for param in method.parameters {
        if let paramDoc = method.paramDocs[param.name], !paramDoc.isEmpty {
            lines.append("- Parameter \(param.name): \(paramDoc)")
        }
    }
    if let returnsDoc = method.returnsDoc, !returnsDoc.isEmpty {
        lines.append("- Returns: \(returnsDoc)")
    }
    guard !lines.isEmpty else { return "" }
    var out = "    /**\n"
    for line in lines { out.append("     \(line)\n") }
    out.append("     */\n")
    return out
}

func resourceTemplateVariables(in template: String) -> [String] {
    guard let regex = try? NSRegularExpression(pattern: "\\{[^}]+\\}") else { return [] }
    let nsRange = NSRange(template.startIndex..., in: template)
    var vars: [String] = []
    for match in regex.matches(in: template, range: nsRange) {
        guard let range = Range(match.range, in: template) else { continue }
        var expr = String(template[range].dropFirst().dropLast())
        if let first = expr.first, "+#./;?&".contains(first) { expr.removeFirst() }
        for spec in expr.split(separator: ",") {
            var name = String(spec)
            if let star = name.firstIndex(of: "*") { name = String(name[..<star]) }
            if let colon = name.firstIndex(of: ":") { name = String(name[..<colon]) }
            if !name.isEmpty, !vars.contains(name) { vars.append(name) }
        }
    }
    return vars
}

func resourceTemplateVariableCount(_ template: String) -> Int {
    resourceTemplateVariables(in: template).count
}
