//
//  SwiftMCPAggregatorTool — main.swift
//
//  Scans target sources for `@MCPExtension("Name") extension <Type> { ... }`
//  attributes and emits a per-target umbrella that calls each one's
//  `<Type>.<Name>.register(in: server)`.
//
//  This tool produces ONLY the umbrella. All metadata extraction, dispatch,
//  and per-tool wiring is done by the macros (`@MCPExtension`,
//  `@MCPExtensionTool`); the umbrella's role is purely to enumerate which
//  extensions exist in the target and pass the server through.
//
//  CLI:
//    SwiftMCPAggregatorTool --module <ModuleName> --output <path> [<input.swift> ...]
//

import Foundation
import SwiftSyntax
import SwiftParser

struct ToolArgs {
    var moduleName: String
    var outputPath: String
    var inputs: [String]
}

func parseArgs(_ argv: [String]) -> ToolArgs {
    var moduleName = ""
    var outputPath = ""
    var inputs: [String] = []
    var i = 1
    while i < argv.count {
        let arg = argv[i]
        switch arg {
        case "--module":
            i += 1
            moduleName = argv[i]
        case "--output":
            i += 1
            outputPath = argv[i]
        default:
            inputs.append(arg)
        }
        i += 1
    }
    return ToolArgs(moduleName: moduleName, outputPath: outputPath, inputs: inputs)
}

struct DiscoveredExtension {
    var extendedType: String
    var name: String
}

final class ExtensionFinder: SyntaxVisitor {
    var extensions: [DiscoveredExtension] = []
    var imports: Set<String> = []

    override func visit(_ node: ImportDeclSyntax) -> SyntaxVisitorContinueKind {
        let path = node.path.map { $0.name.text }.joined(separator: ".")
        if !path.isEmpty { imports.insert(path) }
        return .skipChildren
    }

    override func visit(_ node: ExtensionDeclSyntax) -> SyntaxVisitorContinueKind {
        for attr in node.attributes {
            guard let attrSyntax = attr.as(AttributeSyntax.self),
                  let id = attrSyntax.attributeName.as(IdentifierTypeSyntax.self),
                  id.name.text == "MCPExtension",
                  let argList = attrSyntax.arguments?.as(LabeledExprListSyntax.self),
                  let firstArg = argList.first,
                  let lit = firstArg.expression.as(StringLiteralExprSyntax.self) else { continue }

            extensions.append(DiscoveredExtension(
                extendedType: node.extendedType.trimmedDescription,
                name: lit.segments.description
            ))
            break
        }
        return .visitChildren
    }
}

func sanitize(_ s: String) -> String {
    var out = ""
    for ch in s {
        if ch.isLetter || ch.isNumber || ch == "_" {
            out.append(ch)
        } else {
            out.append("_")
        }
    }
    return out
}

func generateUmbrella(moduleName: String, extensions: [DiscoveredExtension], imports: Set<String>) -> String {
    var out = ""
    out.append("// Generated by SwiftMCPAggregatorTool — DO NOT EDIT.\n")
    out.append("// Bootstrap umbrella for module \(moduleName).\n\n")

    var importsToEmit = imports
    importsToEmit.insert("SwiftMCP")
    importsToEmit.remove(moduleName)
    for imp in importsToEmit.sorted() {
        out.append("import \(imp)\n")
    }
    out.append("\n")

    // Group by extended type so we generate one register(in:) overload per type.
    let grouped = Dictionary(grouping: extensions, by: \.extendedType)
    let sortedTypes = grouped.keys.sorted()

    out.append("public enum SwiftMCPBootstrap_\(sanitize(moduleName)) {\n")

    if extensions.isEmpty {
        out.append("    // no @MCPExtension declarations found in this target\n")
    } else {
        for type in sortedTypes {
            let exts = grouped[type] ?? []
            out.append("    /// Registers all `@MCPExtension`-declared contributions to `\(type)` from this module.\n")
            out.append("    public static func register(in server: \(type)) {\n")
            for ext in exts.sorted(by: { $0.name < $1.name }) {
                out.append("        \(type).\(ext.name).register(in: server)\n")
            }
            out.append("    }\n")
        }
    }

    out.append("}\n")
    return out
}

let args = parseArgs(CommandLine.arguments)
guard !args.moduleName.isEmpty, !args.outputPath.isEmpty else {
    FileHandle.standardError.write(Data("SwiftMCPAggregatorTool: --module and --output are required\n".utf8))
    exit(1)
}

let finder = ExtensionFinder(viewMode: .sourceAccurate)
for path in args.inputs {
    guard let data = try? Data(contentsOf: URL(fileURLWithPath: path)),
          let source = String(data: data, encoding: .utf8) else {
        continue
    }
    let tree = Parser.parse(source: source)
    finder.walk(tree)
}

let generated = generateUmbrella(moduleName: args.moduleName, extensions: finder.extensions, imports: finder.imports)
let outURL = URL(fileURLWithPath: args.outputPath)
try? FileManager.default.createDirectory(at: outURL.deletingLastPathComponent(), withIntermediateDirectories: true)
try generated.write(to: outURL, atomically: true, encoding: .utf8)
