import Foundation

@main
struct SwiftMCPAggregatorTool {
    static func main() throws {
        let args = CommandLine.arguments
        guard args.count >= 2 else {
            fputs("Usage: SwiftMCPAggregatorTool <output-file> [module-names...]\n", stderr)
            exit(2)
        }

        let outputPath = args[1]
        let moduleSlice: [String] = args.count > 2 ? Array(args[2...]) : []
        let modules = Array(Set(moduleSlice)).sorted()

        let importLines = modules
            .filter { $0 != "Foundation" }
            .map { "import \($0)" }
            .joined(separator: "\n")

        var registrationLines: [String] = []
        for module in modules {
            if module == "SwiftMCP" { continue }
            registrationLines.append("        \(module).__SwiftMCPRegistryPluginGenerated.registerAll()")
        }

        let generated = """
        // AUTO-GENERATED by SwiftMCPAggregatorTool. DO NOT EDIT.
        import Foundation
        import SwiftMCP
        \(importLines)

        public enum MCPBootstrap {
            private static let lock = NSLock()
            private nonisolated(unsafe) static var didRegister = false

            public static func registerAll() {
                lock.lock()
                defer { lock.unlock() }

                guard !didRegister else { return }
                didRegister = true

        \(registrationLines.joined(separator: "\n"))
            }
        }
        """

        let outputURL = URL(fileURLWithPath: outputPath)
        try FileManager.default.createDirectory(at: outputURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        try generated.write(to: outputURL, atomically: true, encoding: String.Encoding.utf8)
    }
}
