//
//  MCPExtensionToolMacro.swift
//  SwiftMCPMacros
//
//  Peer macro for `@MCPExtensionTool`. Emits the typed argument-extraction
//  wrapper `__mcpCall_<name>` next to the user's function. Crucially does NOT
//  emit a stored metadata `let` — that's what makes it work in extensions
//  (where stored properties are forbidden). The metadata is generated by the
//  enclosing `@MCPExtension` macro at the extension level.
//

import SwiftSyntax
import SwiftSyntaxMacros
import SwiftDiagnostics

public struct MCPExtensionToolMacro: PeerMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let funcDecl = declaration.as(FunctionDeclSyntax.self) else {
            return []
        }

        let extractor = FunctionMetadataExtractor(funcDecl: funcDecl, context: context)
        let metadata = try extractor.extract()
        let functionName = metadata.functionName

        var wrapperFuncString = "/// Autogenerated wrapper for \(functionName) (extension tool)\n"
        for attribute in metadata.propagatedAttributes {
            wrapperFuncString += "\(attribute)\n"
        }
        wrapperFuncString += "func __mcpCall_\(functionName)(_ enrichedArguments: JSONDictionary) async throws -> (Encodable & Sendable) {\n"

        for detail in metadata.parameters {
            wrapperFuncString += "   let \(detail.name): \(detail.typeString) = try enrichedArguments.extractValue(named: \"\(detail.name)\", as: \(detail.typeString).self)\n"
        }

        let parameterList = metadata.parameters.map { param -> String in
            if param.label == "_" {
                return param.name
            } else {
                return "\(param.label): \(param.name)"
            }
        }.joined(separator: ", ")

        let tryPrefix = metadata.isThrowing ? "try " : ""
        let awaitPrefix = metadata.isAsync ? "await " : ""

        if metadata.returnTypeString == "Void" {
            wrapperFuncString += "   \(tryPrefix)\(awaitPrefix)\(functionName)(\(parameterList))\n"
            wrapperFuncString += "   return \"\"\n"
            wrapperFuncString += "}\n"
        } else {
            wrapperFuncString += "   return \(tryPrefix)\(awaitPrefix)\(functionName)(\(parameterList))\n"
            wrapperFuncString += "}\n"
        }

        return [DeclSyntax(stringLiteral: wrapperFuncString)]
    }
}
