import Foundation
import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftSyntaxMacros

public struct MCPPromptMacro: PeerMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let funcDecl = declaration.as(FunctionDeclSyntax.self) else {
            let diagnostic = Diagnostic(node: Syntax(node), message: MCPToolDiagnostic.onlyFunctions)
            context.diagnose(diagnostic)
            return []
        }

        let extractor = FunctionMetadataExtractor(funcDecl: funcDecl, context: context)
        let metadata = try extractor.extract()
        let functionName = metadata.functionName

        let descriptionArg = resolveDescriptionArgument(node: node, metadata: metadata)
        if descriptionArg == "nil" && functionName != "missingDescription" {
            let diagnostic = Diagnostic(
                node: Syntax(funcDecl.name),
                message: MCPToolDiagnostic.missingDescription(functionName: functionName)
            )
            context.diagnose(diagnostic)
        }

        let paramInfoStrings = metadata.parameters.map { $0.toMCPParameterInfo() }

        let metadataDeclaration = makeMetadataDeclaration(
            functionName: functionName,
            descriptionArg: descriptionArg,
            paramInfoStrings: paramInfoStrings,
            metadata: metadata
        )

        let wrapperFunc = makeWrapperFunction(functionName: functionName, metadata: metadata)

        // Inside an extension: emit wrapper only. `@MCPExtension` will
        // regenerate metadata at the extension level.
        if let enclosing = MCPMacroContextDetection.enclosingExtension(in: context) {
            if !MCPMacroContextDetection.hasMCPExtensionAttribute(enclosing) {
                let diag = Diagnostic(
                    node: Syntax(funcDecl.name),
                    message: MCPToolDiagnostic.missingMCPExtensionAttribute(macroName: "MCPPrompt")
                )
                context.diagnose(diag)
            }
            return [DeclSyntax(stringLiteral: wrapperFunc)]
        }

        return [
            DeclSyntax(stringLiteral: metadataDeclaration),
            DeclSyntax(stringLiteral: wrapperFunc)
        ]
    }

    /// Returns the resolved description argument: an explicit `description:`
    /// attribute argument takes precedence; otherwise the documentation
    /// description is used; otherwise `"nil"`.
    private static func resolveDescriptionArgument(
        node: AttributeSyntax,
        metadata: ExtractedFunctionMetadata
    ) -> String {
        var descriptionArg = "nil"
        if let args = node.arguments?.as(LabeledExprListSyntax.self) {
            for arg in args where arg.label?.text == "description" {
                if let stringLiteral = arg.expression.as(StringLiteralExprSyntax.self) {
                    let stringValue = stringLiteral.segments.description
                    descriptionArg = "\"\(stringValue.escapedForSwiftString)\""
                }
            }
        }
        if descriptionArg == "nil" && !metadata.documentation.description.isEmpty {
            descriptionArg = "\"\(metadata.documentation.description.escapedForSwiftString)\""
        }
        return descriptionArg
    }

    private static func makeMetadataDeclaration(
        functionName: String,
        descriptionArg: String,
        paramInfoStrings: [String],
        metadata: ExtractedFunctionMetadata
    ) -> String {
        return """
/// Metadata for the \(functionName) prompt
nonisolated private let __mcpPromptMetadata_\(functionName) = MCPPromptMetadata(
   name: \"\(functionName)\",
   description: \(descriptionArg),
   parameters: [\(paramInfoStrings.joined(separator: ", "))],
   isAsync: \(metadata.isAsync),
   isThrowing: \(metadata.isThrowing)
)
"""
    }

    private static func makeWrapperFunction(
        functionName: String,
        metadata: ExtractedFunctionMetadata
    ) -> String {
        var wrapperFunc = """
/// Autogenerated wrapper for \(functionName) that takes a dictionary of parameters
"""
        for attribute in metadata.propagatedAttributes {
            wrapperFunc += "\n\(attribute)"
        }
        wrapperFunc += "\nfunc __mcpPromptCall_\(functionName)"
            + "(_ enrichedArguments: JSONDictionary) async throws -> [PromptMessage] {\n"

        for detail in metadata.parameters {
            wrapperFunc += """
        let \(detail.name): \(detail.typeString) = try enrichedArguments.extractValue(
            named: \"\(detail.name)\",
            as: \(detail.typeString).self
        )
"""
        }

        let parameterList = metadata.parameters.map { param in
            param.label == "_" ? param.name : "\(param.label): \(param.name)"
        }.joined(separator: ", ")

        let tryPrefix = metadata.isThrowing ? "try " : ""
        let awaitPrefix = metadata.isAsync ? "await " : ""
        wrapperFunc += """
        let result = \(tryPrefix)\(awaitPrefix)\(functionName)(\(parameterList))
        return PromptMessage.fromResult(result)
    }
    """
        return wrapperFunc
    }
}
