//
//  MCPResourceMacro+Emission.swift
//  SwiftMCPMacros
//
//  Code emission helpers for `@MCPResource`: builds the metadata `let` and
//  the wrapper method that bridges JSON arguments to the user's function.
//

import Foundation
import SwiftSyntax

extension MCPResourceMacro {
    static func makeMetadataDeclaration(
        functionName: String,
        attrArgs: ResourceAttributeArgs,
        descriptionArg: String,
        parameterInfoStrings: [String],
        commonMetadata: ExtractedFunctionMetadata
    ) -> String {
        let templatesSetString = "[\(attrArgs.templates.map { "\"\($0)\"" }.joined(separator: ", "))]"
        let returnDescriptionString = commonMetadata.returnDescription ?? "nil"
        return """
/// Metadata for the \(functionName) resource
nonisolated private let __mcpResourceMetadata_\(functionName) = MCPResourceMetadata(
   uriTemplates: Set(\(templatesSetString)),
   name: "\(attrArgs.resourceName)",
   functionName: "\(functionName)",
   description: \(descriptionArg),
   parameters: [\(parameterInfoStrings.joined(separator: ", "))],
   returnType: \(commonMetadata.returnTypeString).self,
   returnTypeDescription: \(returnDescriptionString),
   isAsync: \(commonMetadata.isAsync),
   isThrowing: \(commonMetadata.isThrowing),
   mimeType: \(attrArgs.mimeTypeArg)
)
"""
    }

    static func makeWrapperMethod(
        functionName: String,
        commonMetadata: ExtractedFunctionMetadata,
        wrapperParamDetails: [WrapperParamDetail]
    ) -> String {
        let callParameterList = wrapperParamDetails.map { param in
            param.label == "_" ? param.name : "\(param.label): \(param.name)"
        }.joined(separator: ", ")

        var wrapperMethod = """

        /// Autogenerated wrapper for \(functionName) that takes a dictionary of parameters and URI
"""
        for attribute in commonMetadata.propagatedAttributes {
            wrapperMethod += "\n        \(attribute)"
        }
        wrapperMethod += "\n        private func __mcpResourceCall_\(functionName)"
            + "(_ params: JSONDictionary, "
            + "requestedUri: URL, "
            + "overrideMimeType: String?) async throws -> [MCPResourceContent] {\n"

        for detail in wrapperParamDetails {
            wrapperMethod += """
                let \(detail.name): \(detail.type) = try params.extractValue(
                    named: "\(detail.name)",
                    as: \(detail.type).self
                )
            """
        }

        let tryPrefix = commonMetadata.isThrowing ? "try " : ""
        let awaitPrefix = commonMetadata.isAsync ? "await " : ""
        let concreteFunctionCall = "\(tryPrefix)\(awaitPrefix)\(functionName)(\(callParameterList))"
        let returnHandlingCode = makeReturnHandlingCode(
            returnTypeString: commonMetadata.returnTypeString,
            concreteFunctionCall: concreteFunctionCall
        )

        wrapperMethod += """
        \(returnHandlingCode)
        }
        """
        return wrapperMethod
    }

    /// Generates the return-handling code for the resource wrapper based on
    /// the function's return type.
    static func makeReturnHandlingCode(
        returnTypeString: String,
        concreteFunctionCall: String
    ) -> String {
        let concreteResourceContentTypeName = "GenericResourceContent"
        switch returnTypeString {
        case "String":
            return """
                let result = \(concreteFunctionCall)
                return [\(concreteResourceContentTypeName)(
                    uri: requestedUri,
                    mimeType: overrideMimeType ?? "text/plain",
                    text: result
                )]
            """
        case "Data":
            return """
                let result = \(concreteFunctionCall)
                return [\(concreteResourceContentTypeName)(
                    uri: requestedUri,
                    mimeType: overrideMimeType ?? "application/octet-stream",
                    blob: result
                )]
            """
        case "MCPResourceContent":
            return """
                let result = \(concreteFunctionCall)
                return [result]
            """
        case "[MCPResourceContent]", "[\(concreteResourceContentTypeName)]":
            return """
                let result = \(concreteFunctionCall)
                return result
            """
        default:
            return """
                let result = \(concreteFunctionCall)
                return GenericResourceContent.fromResult(
                    result,
                    uri: requestedUri,
                    mimeType: overrideMimeType
                )
            """
        }
    }
}
