import Foundation
import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftSyntaxMacros

/// Implementation of the `MCPResource` macro used to expose read-only resources.
///
/// This macro transforms a function into an MCP resource by generating metadata and wrapper
/// functions for parameter handling and type safety.
///
/// Example usage:
/// ```swift
/// @MCPResource("users://{user_id}/profile?locale={lang}")
/// func getUserProfile(user_id: Int, lang: String = "en") -> ProfileResource
/// ```
public struct MCPResourceMacro: PeerMacro {
    struct WrapperParamDetail {
        let name: String
        let label: String
        let type: String
    }

    /// Resource-attribute arguments parsed from `@MCPResource(...)`.
    struct ResourceAttributeArgs {
        var templates: [String]
        var resourceName: String
        var mimeTypeArg: String
    }

    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let funcDecl = declaration.as(FunctionDeclSyntax.self) else {
            let diag = Diagnostic(node: Syntax(node), message: MCPResourceDiagnostic.onlyFunctions)
            context.diagnose(diag)
            return []
        }

        let extractor = FunctionMetadataExtractor(funcDecl: funcDecl, context: context)
        let commonMetadata = try extractor.extract()

        guard let attrArgs = parseAttributeArguments(
            node: node,
            functionName: commonMetadata.functionName,
            context: context
        ) else {
            return []
        }

        diagnoseAttributeAndParameters(
            attrArgs: attrArgs,
            commonMetadata: commonMetadata,
            node: node,
            context: context
        )

        return try emitDeclarations(
            funcDecl: funcDecl,
            attrArgs: attrArgs,
            commonMetadata: commonMetadata,
            context: context
        )
    }

    /// Runs validation and diagnostic emission against the parsed attribute
    /// arguments and the function's parameters.
    private static func diagnoseAttributeAndParameters(
        attrArgs: ResourceAttributeArgs,
        commonMetadata: ExtractedFunctionMetadata,
        node: AttributeSyntax,
        context: some MacroExpansionContext
    ) {
        validateTemplates(templates: attrArgs.templates, node: node, context: context)
        let allPlaceholders = collectPlaceholders(from: attrArgs.templates)
        let functionParamNames = commonMetadata.parameters.map { $0.name }

        diagnoseMissingParameters(
            placeholders: allPlaceholders,
            functionParamNames: functionParamNames,
            node: node,
            context: context
        )
        diagnoseUnknownPlaceholders(
            functionParamNames: functionParamNames,
            placeholders: allPlaceholders,
            metadata: commonMetadata,
            context: context
        )
    }

    /// Builds the metadata-and-wrapper declarations. When expanded inside an
    /// extension, only the wrapper is emitted (the metadata is regenerated by
    /// `@MCPExtension`).
    private static func emitDeclarations(
        funcDecl: FunctionDeclSyntax,
        attrArgs: ResourceAttributeArgs,
        commonMetadata: ExtractedFunctionMetadata,
        context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        let descriptionArg = makeDescriptionArg(from: commonMetadata)
        let wrapperDetails = makeWrapperDetails(from: commonMetadata)

        let metadataDeclaration = makeMetadataDeclaration(
            functionName: commonMetadata.functionName,
            attrArgs: attrArgs,
            descriptionArg: descriptionArg,
            parameterInfoStrings: wrapperDetails.parameterInfoStrings,
            commonMetadata: commonMetadata
        )

        let wrapperMethod = makeWrapperMethod(
            functionName: commonMetadata.functionName,
            commonMetadata: commonMetadata,
            wrapperParamDetails: wrapperDetails.wrapperParamDetails
        )

        if let enclosing = MCPMacroContextDetection.enclosingExtension(in: context) {
            if !MCPMacroContextDetection.hasMCPExtensionAttribute(enclosing) {
                let diag = Diagnostic(
                    node: Syntax(funcDecl.name),
                    message: MCPToolDiagnostic.missingMCPExtensionAttribute(macroName: "MCPResource")
                )
                context.diagnose(diag)
            }
            return [DeclSyntax(stringLiteral: wrapperMethod)]
        }

        return [
            DeclSyntax(stringLiteral: metadataDeclaration),
            DeclSyntax(stringLiteral: wrapperMethod)
        ]
    }
}
