import Foundation
import SwiftMCP

@MCPTool
class Calculator {
    /// Adds two integers and returns their sum
    /// - Parameter a: First number to add
    /// - Parameter b: Second number to add
    /// - Returns: The sum of a and b
    @MCPFunction
    func add(a: Int, b: Int) -> Int {
        return a + b
    }
    
    /// Subtracts the second integer from the first and returns the difference
    /// - Parameter a: Number to subtract from
    /// - Parameter b: Number to subtract
    /// - Returns: The difference between a and b
    @MCPFunction
    func subtract(a: Int, b: Int) -> Int {
        return a - b
    }
	
    /** 
     A test function that processes an array of integers
     - Parameter a: Array of integers to process
     */
	@MCPFunction
	func testArray(a: [Int]) {
		
	}
    
    /**
     Multiplies two integers and returns their product
     - Parameter a: First factor
     - Parameter b: Second factor
     - Returns: The product of a and b
     */
    @MCPFunction
    func multiply(a: Int, b: Int) -> Int {
        return a * b
    }
    
    /// Divides the numerator by the denominator and returns the quotient
    /// - Parameter numerator: Number to be divided
    /// - Parameter denominator: Number to divide by
    /// - Returns: The quotient of numerator divided by denominator
    @MCPFunction
    func divide(numerator: Double, denominator: Double) -> Double {
        return numerator / denominator
    }
    
    /// Prints a greeting message with the provided name
    /// - Parameter name: Name of the person to greet
    @MCPFunction
    func greet(name: String) {
        print("Hello, \(name)!")
    }
	
    /** A simple ping function that returns 'pong' */
	@MCPFunction
	func ping() -> String {
		return "pong"
	}
    
    // Initialize the calculator class
    init() {
        // No manual registration needed - metadata is generated by the macro
    }
    
    // Demonstrate the functions
    func demonstrateFunctions() {
        print("Function Demonstrations:")
        print("2 + 3 = \(add(a: 2, b: 3))")
        print("5 - 2 = \(subtract(a: 5, b: 2))")
        print("4 * 6 = \(multiply(a: 4, b: 6))")
        print("10 / 2 = \(divide(numerator: 10, denominator: 2))")
        greet(name: "Swift Developer!")
    }
} 
