name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Swift 5.9
        uses: swift-actions/setup-swift@v2.2.0
        with:
          swift-version: "5.9"

      - name: Verify Swift version
        run: swift --version
      
      - name: Build & Test
        run: swift test

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Swift 5.9
        uses: swift-actions/setup-swift@v2.2.0
        with:
          swift-version: "5.9"

      - name: Verify Swift version
        run: swift --version
      
      - name: Build & Test
        run: swift test 
